[package]
name = "adder"
version = "0.1.0"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "wasm"
path = "src/lib.rs"


[dependencies]
elrond-wasm = "0.1.0"
elrond-wasm-node = "0.1.0"
elrond-wasm-derive = "0.1.0"
